### ISSUE TITLE
ImportError: libpython3.5m.so.1.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by yashbhutwala** [CoatiSoftware/SourcetrailPythonIndexer#10]
Running version python3.5.6 on Ubuntu.  Maybe it's just something simple I need to fix with my setup, but here's the traceback.  I would like to use this for my own project, would love the help to set it up properly.

> command "/home/ybhutwala/virtualenvs/SourcetrailPythonIndexer-3.5/bin/python /home/ybhutwala/sources/SourcetrailPythonIndexer/run.py --source-file-path="/home/ybhutwala/Projects/dimensions_profiles/dimensions_profiles/__init__.py" --database-file-path="/home/ybhutwala/SourcetrailProjects/dimensions-profiles.srctrldb_tmp"" returned code "1" with message "" and output "Traceback (most recent call last):   File "/home/ybhutwala/sources/SourcetrailPythonIndexer/run.py", line 2, in <module>     import indexer   File "/home/ybhutwala/sources/SourcetrailPythonIndexer/indexer.py", line 6, in <module>     import sourcetraildb as srctrl   File "/home/ybhutwala/sources/SourcetrailPythonIndexer/sourcetraildb.py", line 28, in <module>     _sourcetraildb = swig_import_helper()   File "/home/ybhutwala/sources/SourcetrailPythonIndexer/sourcetraildb.py", line 24, in swig_import_helper     _mod = imp.load_module('_sourcetraildb', fp, pathname, description)   File "/home/ybhutwala/virtualenvs/SourcetrailPythonIndexer-3.5/lib/python3.5/imp.py", line 243, in load_module     return load_dynamic(name, filename, file)   File "/home/ybhutwala/virtualenvs/SourcetrailPythonIndexer-3.5/lib/python3.5/imp.py", line 343, in load_dynamic     return _load(spec) ImportError: libpython3.5m.so.1.0: cannot open shared object file: No such file or directory".

**Comment by egraether** [comment]
Did you also put the `_sourcetraildb.so` in the root directory together with the `sourcetraildb.py' file?

Did you download the SourcetrailDB python binding from the [releases](https://github.com/CoatiSoftware/SourcetrailDB/releases), or did you build it yourself?

**Comment by yashbhutwala** [comment]
Yes I'm on Ubuntu 18.04 and I downloaded the `sourcetraildb_python35_v1_db23_p0-linux-64bit-gcc.zip` binding, and I put both `_sourcetraildb.so` and `sourcetraildb.py` in the `SourcetrailPythonIndexer` directory.

**Comment by egraether** [comment]
I did some online research. There is a small chance that it's a library path lookup issue. Can you please add the SourcetrailPythonIndexer directory to your `LD_LIBRARY_PATH` then execute `run.py` again:
```
export LD_LIBRARY_PATH=/home/ybhutwala/sources/SourcetrailPythonIndexer:$LD_LIBRARY_PATH
``` 

But more likely this is a compatibility issue of the `_sourcetraildb.so` binary file with your machine. You might have to build the SourctrailDB Python Binding yourself (see [instructions](https://github.com/CoatiSoftware/SourcetrailDB#python-bindings)). It's pretty easy, but you need [Cmake](https://cmake.org/) and [SWIG](http://www.swig.org/).

**Comment by yashbhutwala** [comment]
Adding `LD_LIBRARY_PATH` did not work for me, but building the binding from source worked, even for Python 3.6.  Thanks @egraether!  It works wonderfully so far, but I'll report any bugs if I find.
