### ISSUE TITLE
Local method variable marked as "ambiguous" when it should be locally scoped

### ISSUE THREAD

**Issue by madig** [CoatiSoftware/SourcetrailPythonIndexer#45]
1. Index https://github.com/fonttools/fonttools/tree/master/Lib/fontTools (install in local venv with `pip install -e .[all]`
2. Navigate to `fontTools.varLib.merger.Merger.mergeTables`:

```Python
    def mergeTables(self, font, master_ttfs, tableTags):

        for tag in tableTags:
            if tag not in font:
                continue
            self.mergeThings(
                font[tag], [m[tag] if tag in m else None for m in master_ttfs]
            )
```

Sourcetrail or an underlying library goes off and marks `tag` as ambiguous and points to other classes like `AxisDescriptor` etc., when the variable should clearly be locally scoped:
![asas](https://user-images.githubusercontent.com/380829/58885724-9ad2a780-86da-11e9-930c-1a058d0f5691.png)
Or am I missing some Python scoping nuance here?

**Comment by egraether** [comment]
Thanks for reporting @madig!
This is a known issue and already open with #26.
Closing due to duplicate
