### ISSUE TITLE
Modules within PYTHONPATH not found

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/SourcetrailPythonIndexer#46]
https://docs.python.org/2/using/cmdline.html#envvar-PYTHONPATH

reported via mail

**Comment by mlangkabel** [comment]
I just tested this for Sourcetrail 2019.2.39 on Windows and found that Sourcetrail alreads respects the PYTHONPATH environment variable. If anyone experiences a different behavior, please let us know.
