### ISSUE TITLE
McAfee reports 'BehavesLike.Win32.Generic.tc' when downloading Windows release package

### ISSUE THREAD

**Issue by egraether** [CoatiSoftware/SourcetrailPythonIndexer#48]

**Comment by mlangkabel** [comment]
This seems to be a false positive caused by Pyinstaller which is used to freeze the SourcetrailPythonIndexer package: https://www.virustotal.com/gui/file/471bc7ccd2c231d8d7c3105108defa5f79daee69242be27ceb02569228a5dceb/detection

**Comment by mlangkabel** [comment]
Fixed with merge of pull request #51 by using a self-built version of the pyinstaller bootloader as suggested by [this stackoverflow answer](https://stackoverflow.com/a/52054580/2797295).
