### ISSUE TITLE
Python project full of Return -1 errors, with 0 errors counted after indexing

### ISSUE THREAD

**Issue by brodders61** [CoatiSoftware/SourcetrailPythonIndexer#63]
Hi,
continuing a major project now in Year 5. This is about the 6th machine development has been hosted on; this is a power electrics simulator written in python 2.7 now running on Windows 8.1, with Anaconda/Spyder as the dev environment. I'm more into electrics than software, although I've written a lot of python now. This simulator has spent several years running and (in present form) works.

Have come across Sourcetrail which looks useful. However cannot successfully index my work. Lots of lacunae:

1. Splash message: Finished Indexing comes up as indexing still running...?
2. Lots of ERROR messages all "returned code '-1'"
3. Summary of project: 0 files, 0 errors!
4. Although an exclusion of *Copy* set up, there are plenty of filenames with Copy in them being processed. Hm; 
![AllFinished!_at_81%](https://user-images.githubusercontent.com/12859315/76704636-48df9900-66d2-11ea-8284-8db67486b443.png)
![processingCOPYfile](https://user-images.githubusercontent.com/12859315/76704638-4d0bb680-66d2-11ea-9063-423fa3354b8e.png)

what am I doing wrong ?

Thanks for your help!

**Comment by mlangkabel** [comment]
Hi @brodders61, thanks for reaching out. 
* which version of Sourcetrail are you using?
* did you try "shallow indexing"? You can activate it via ticking the box in the "start indexing" dialog? What happens if you do that?
* can you try to manually run one of the failed commands in a console? Does it provide more information than just "-1"?

**Comment by brodders61** [comment]
Hi,

Latest 64 bit version as of Sunday (2019_04_102_64). Shallow indexing helps a lot! Why not ticked by default? :)

Was hoping the system would help with tracing data not processes; processes easy but behind the scenes data mods not so visible, as far as I can see. Depends on across project absolute variable naming :( So, might be useful...

Thanks for feedback!
